2019-06-21 14:43:53,057 ERROR: Exception on /image/remove [POST] [in /Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/aisino/Projects/DockerManager/app/image/routes.py", line 61, in remove_images
    result = services.remove_images(endpoint_id, image_hashs)
  File "/Users/aisino/Projects/DockerManager/app/image/services.py", line 124, in remove_images
    url = Endpoint.query.get(endpoint_id).urls
AttributeError: 'Endpoint' object has no attribute 'urls'
2019-06-21 14:44:10,382 INFO: Aisino Docker Manager startup [in /Users/aisino/Projects/DockerManager/app/__init__.py:79]
2019-06-21 14:44:19,803 ERROR: Exception on /image/remove [POST] [in /Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/aisino/Projects/DockerManager/app/image/routes.py", line 61, in remove_images
    result = services.remove_images(endpoint_id, image_hashs)
  File "/Users/aisino/Projects/DockerManager/app/image/services.py", line 142, in remove_images
    image_in_db = images_in_db[image_hash]
KeyError: 'sha256:415381a6cb813ef0972eff8edac32069637b4546349d9ffdb8e4f641f55edcdd'
