2019-06-21 14:34:14,665 ERROR: Exception on /image/remove [POST] [in /Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/aisino/Projects/DockerManager/app/image/routes.py", line 61, in remove_images
    result = services.remove_images(endpoint_id, image_hashs)
  File "/Users/aisino/Projects/DockerManager/app/image/services.py", line 124, in remove_images
    url = Endpoint.query.get(endpoint_id).first().url
AttributeError: 'Endpoint' object has no attribute 'first'
2019-06-21 14:37:11,004 INFO: Aisino Docker Manager startup [in /Users/aisino/Projects/DockerManager/app/__init__.py:79]
2019-06-21 14:37:21,578 INFO: Aisino Docker Manager startup [in /Users/aisino/Projects/DockerManager/app/__init__.py:79]
2019-06-21 14:37:33,457 ERROR: Exception on /image/remove [POST] [in /Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/aisino/Projects/DockerManager/app/image/routes.py", line 61, in remove_images
    result = services.remove_images(endpoint_id, image_hashs)
  File "/Users/aisino/Projects/DockerManager/app/image/services.py", line 124, in remove_images
    url = Endpoint.query.get(endpoint_id).urls
AttributeError: 'Endpoint' object has no attribute 'urls'
2019-06-21 14:39:27,669 INFO: Aisino Docker Manager startup [in /Users/aisino/Projects/DockerManager/app/__init__.py:79]
2019-06-21 14:39:44,853 ERROR: Exception on /image/remove [POST] [in /Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/aisino/Projects/DockerManager/app/image/routes.py", line 61, in remove_images
    result = services.remove_images(endpoint_id, image_hashs)
  File "/Users/aisino/Projects/DockerManager/app/image/services.py", line 124, in remove_images
    url = Endpoint.query.get(endpoint_id).urls
AttributeError: 'Endpoint' object has no attribute 'urls'
2019-06-21 14:41:47,650 INFO: Aisino Docker Manager startup [in /Users/aisino/Projects/DockerManager/app/__init__.py:79]
2019-06-21 14:42:12,223 ERROR: Exception on /image/remove [POST] [in /Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/aisino/Projects/DockerManager/app/image/routes.py", line 61, in remove_images
    result = services.remove_images(endpoint_id, image_hashs)
  File "/Users/aisino/Projects/DockerManager/app/image/services.py", line 124, in remove_images
    url = Endpoint.query.get(endpoint_id).urls
AttributeError: 'Endpoint' object has no attribute 'urls'
2019-06-21 14:43:21,785 INFO: Aisino Docker Manager startup [in /Users/aisino/Projects/DockerManager/app/__init__.py:79]
2019-06-21 14:43:41,120 ERROR: Exception on /image/remove [POST] [in /Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/aisino/Projects/DockerManager/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/aisino/Projects/DockerManager/app/image/routes.py", line 61, in remove_images
    result = services.remove_images(endpoint_id, image_hashs)
  File "/Users/aisino/Projects/DockerManager/app/image/services.py", line 124, in remove_images
    url = Endpoint.query.get(endpoint_id).urls
AttributeError: 'Endpoint' object has no attribute 'urls'
